In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('ipl.csv')
pd.set_option('display.max_columns', None)
df.head(50)

C:\Users\admin\AppData\Local\Temp\ipykernel_8376\896356783.py:1: DtypeWarning: Columns (1,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('ipl.csv')

,match_id,season,date,city,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,player_of_match,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,runs_scored,extras,current_score,wickets_down,balls_remaining,wickets_remaining,current_run_rate,required_run_rate,target_score,wicket_kind,player_out,fielder
0,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0,119,10,6.00,NaN,NaN,NaN,NaN,NaN
1,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,1,0,118,10,3.00,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,2,0,118,10,6.00,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,2,0,117,10,4.00,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,2,0,116,10,3.00,NaN,NaN,NaN,NaN,NaN
5,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,2,0,115,10,2.40,NaN,NaN,NaN,NaN,NaN
6,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,3,0,114,10,3.00,NaN,NaN,NaN,NaN,NaN
7,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,3,0,113,10,2.57,NaN,NaN,NaN,NaN,NaN
8,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,7,0,112,10,5.25,NaN,NaN,NaN,NaN,NaN
9,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,11,0,111,10,7.33,NaN,NaN,NaN,NaN,NaN
10,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,0,17,0,110,10,10.20,NaN,NaN,NaN,NaN,NaN
11,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,SC Ganguly,4,0,21,0,109,10,11.45,NaN,NaN,NaN,NaN,NaN
12,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,Z Khan,SC Ganguly,0,0,21,0,108,10,10.50,NaN,NaN,NaN,NaN,NaN
13,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,SC Ganguly,P Kumar,BB McCullum,0,0,21,0,107,10,9.69,NaN,NaN,NaN,NaN,NaN
14,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,SC Ganguly,P Kumar,BB McCullum,0,0,21,0,106,10,9.00,NaN,NaN,NaN,NaN,NaN
15,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,BB McCullum,0,1,22,0,105,10,8.80,NaN,NaN,NaN,NaN,NaN
16,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,SC Ganguly,4,0,26,0,104,10,9.75,NaN,NaN,NaN,NaN,NaN
17,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,P Kumar,SC Ganguly,1,0,27,0,103,10,9.53,NaN,NaN,NaN,NaN,NaN
18,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,SC Ganguly,P Kumar,BB McCullum,0,0,27,0,102,10,9.00,NaN,NaN,NaN,NaN,NaN
19,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,SC Ganguly,0,5,32,0,102,10,10.67,NaN,NaN,NaN,NaN,NaN
20,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,BB McCullum,AA Noffke,SC Ganguly,6,0,38,0,101,10,12.00,NaN,NaN,NaN,NaN,NaN
21,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,3,BB McCullum,AA Noffke,SC Ganguly,0,1,39,0,100,10,11.70,NaN,NaN,NaN,NaN,NaN
22,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,4,SC Ganguly,AA Noffke,BB McCullum,4,0,43,0,99,10,12.29,NaN,NaN,NaN,NaN,NaN
23,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,5,SC Ganguly,AA Noffke,BB McCullum,0,0,43,0,98,10,11.73,NaN,NaN,NaN,NaN,NaN
24,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,6,SC Ganguly,AA Noffke,BB McCullum,1,0,44,0,97,10,11.48,NaN,NaN,NaN,NaN,NaN
25,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,7,BB McCullum,AA Noffke,SC Ganguly,6,0,50,0,96,10,12.50,NaN,NaN,NaN,NaN,NaN
26,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,1,SC Ganguly,P Kumar,BB McCullum,4,0,54,0,95,10,12.96,NaN,NaN,NaN,NaN,NaN
27,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,2,SC Ganguly,P Kumar,BB McCullum,1,0,55,0,94,10,12.69,NaN,NaN,NaN,NaN,NaN
28,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,3,BB McCullum,P Kumar,SC Ganguly,4,0,59,0,93,10,13.11,NaN,NaN,NaN,NaN,NaN
29,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,4,BB McCullum,P Kumar,SC Ganguly,0,0,59,0,92,10,12.64,NaN,NaN,NaN,NaN,NaN
30,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,5,BB McCullum,P Kumar,SC Ganguly,1,0,60,0,91,10,12.41,NaN,NaN,NaN,NaN,NaN
31,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,6,SC Ganguly,P Kumar,BB McCullum,0,0,60,0,90,10,12.00,NaN,NaN,NaN,NaN,NaN
32,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,1,BB McCullum,Z Khan,SC Ganguly,1,0,61,0,89,10,11.81,NaN,NaN,NaN,NaN,NaN
33,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,2,SC Ganguly,Z Khan,BB McCullum,0,0,61,1,88,9,11.44,NaN,NaN,caught,SC Ganguly,JH Kallis
34,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,3,RT Ponting,Z Khan,BB McCullum,0,0,61,1,87,9,11.09,NaN,NaN,NaN,NaN,NaN
35,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,4,RT Ponting,Z Khan,BB McCullum,0,0,61,1,86,9,10.76,NaN,NaN,NaN,NaN,NaN
36,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,5,RT Ponting,Z Khan,BB McCullum,0,0,61,1,85,9,10.46,NaN,NaN,NaN,NaN,NaN
37,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,6,RT Ponting,Z Khan,BB McCullum,0,0,61,1,84,9,10.17,NaN,NaN,NaN,NaN,NaN
38,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,1,BB McCullum,AA Noffke,RT Ponting,1,0,62,1,83,9,10.05,NaN,NaN,NaN,NaN,NaN
39,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,2,RT Ponting,AA Noffke,BB McCullum,1,0,63,1,82,9,9.95,NaN,NaN,NaN,NaN,NaN
40,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,3,BB McCullum,AA Noffke,RT Ponting,1,0,64,1,81,9,9.85,NaN,NaN,NaN,NaN,NaN
41,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,4,RT Ponting,AA Noffke,BB McCullum,2,0,66,1,80,9,9.90,NaN,NaN,NaN,NaN,NaN
42,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,5,RT Ponting,AA Noffke,BB McCullum,1,0,67,1,79,9,9.80,NaN,NaN,NaN,NaN,NaN
43,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,6,BB McCullum,AA Noffke,RT Ponting,1,0,68,1,78,9,9.71,NaN,NaN,NaN,NaN,NaN
44,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,1,BB McCullum,Z Khan,RT Ponting,0,0,68,1,77,9,9.49,NaN,NaN,NaN,NaN,NaN
45,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,2,BB McCullum,Z Khan,RT Ponting,1,0,69,1,76,9,9.41,NaN,NaN,NaN,NaN,NaN
46,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,3,RT Ponting,Z Khan,BB McCullum,1,0,70,1,75,9,9.33,NaN,NaN,NaN,NaN,NaN
47,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,4,BB McCullum,Z Khan,RT Ponting,1,0,71,1,74,9,9.26,NaN,NaN,NaN,NaN,NaN
48,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,5,RT Ponting,Z Khan,BB McCullum,1,0,72,1,73,9,9.19,NaN,NaN,NaN,NaN,NaN
49,335982,2007/08,4/18/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140,BB McCullum,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,6,BB McCullum,Z Khan,RT Ponting,1,0,73,1,72,9,9.13,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           278205 non-null  int64
 1   season             278205 non-null  object
 2   date               278205 non-null  object
 3   city               265808 non-null  object
 4   venue              278205 non-null  object
 5   team1              278205 non-null  object
 6   team2              278205 non-null  object
 7   toss_winner        278205 non-null  object
 8   toss_decision      278205 non-null  object
 9   winner             273503 non-null  object
 10  result             278205 non-null  object
 11  result_margin      278205 non-null  object
 12  player_of_match    277399 non-null  object
 13  inning             278205 non-null  int64
 14  batting_team       278205 non-null  object
 15  bowling_team       278205 non-null  object
 16  over               278205 non-null  int64
 17  ball               278205 non-null  int64
 18  batter             278205 non-null  object
 19  bowler             278205 non-null  object
 20  non_striker        278205 non-null  object
 21  runs_scored        278205 non-null  int64
 22  extras             278205 non-null  int64
 23  current_score      278205 non-null  int64
 24  wickets_down       278205 non-null  int64
 25  balls_remaining    278205 non-null  int64
 26  wickets_remaining  278205 non-null  int64
 27  current_run_rate   278205 non-null  float64
 28  required_run_rate  133903 non-null  float64
 29  target_score       133903 non-null  float64
 30  wicket_kind        13823 non-null   object
 31  player_out         13823 non-null   object
 32  fielder            10013 non-null   object
dtypes: float64(3), int64(10), object(20)
memory usage: 70.0+ MB

In [4]:
for col in df.select_dtypes(include='object').columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- season ---
season
2013       18177
2022       17912
2023       17863
2012       17767
2025       17285
2024       17103
2020/21    14559
2009/10    14498
2019       14312
2014       14300
2016       14096
2017       13862
2015       13652
2009       13606
2007/08    13489
2018       13380
2021       11434
2011        9454
2011        7559
2021        2991
2018         906
Name: count, dtype: int64

--- date ---
date
10/18/2020    520
4/8/2025      517
4/23/2009     513
4/30/2023     510
4/25/2021     510
             ...
5/13/2015     126
5/5/2025      123
5/15/2015     106
5/8/2025       63
4/30/2019      51
Name: count, Length: 885, dtype: int64

--- city ---
city
Mumbai            43374
Kolkata           23436
Delhi             22993
Chennai           22132
Hyderabad         19664
Jaipur            15194
Bangalore         14907
Chandigarh        14476
Pune              12239
Ahmedabad         10816
Abu Dhabi          8799
Bengaluru          8043
Lucknow            5235
Visakhapatnam      4000
Durban             3643
Dharamsala         3457
Dubai              3149
Centurion          2866
Rajkot             2381
Sharjah            2355
Navi Mumbai        2188
Mohali             2166
Indore             1965
Johannesburg       1940
Cuttack            1695
Port Elizabeth     1677
Ranchi             1671
Cape Town          1539
Raipur             1431
Guwahati           1223
Kochi              1155
Kanpur              921
Nagpur              742
Kimberley           726
East London         715
Bloemfontein        500
New Chandigarh      395
Name: count, dtype: int64

--- venue ---
venue
Eden Gardens                                                               17988
Wankhede Stadium                                                           17591
M Chinnaswamy Stadium                                                      14907
Feroz Shah Kotla                                                           13950
Wankhede Stadium, Mumbai                                                   12547
MA Chidambaram Stadium, Chepauk                                            11760
Rajiv Gandhi International Stadium, Uppal                                  11604
Dubai International Cricket Stadium                                        11229
Sawai Mansingh Stadium                                                     11150
Punjab Cricket Association Stadium, Mohali                                  8266
MA Chidambaram Stadium, Chepauk, Chennai                                    8242
Narendra Modi Stadium, Ahmedabad                                            7923
Sheikh Zayed Stadium                                                        6925
Sharjah Cricket Stadium                                                     6672
Arun Jaitley Stadium, Delhi                                                 5687
Eden Gardens, Kolkata                                                       5448
Maharashtra Cricket Association Stadium                                     5294
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow       5235
Dr DY Patil Sports Academy, Mumbai                                          4905
M Chinnaswamy Stadium, Bengaluru                                            4549
Rajiv Gandhi International Stadium, Uppal, Hyderabad                        4451
Brabourne Stadium, Mumbai                                                   4057
Sawai Mansingh Stadium, Jaipur                                              4044
Dr DY Patil Sports Academy                                                  3993
Subrata Roy Sahara Stadium                                                  3825
Kingsmead                                                                   3643
Rajiv Gandhi International Stadium                                          3609
M.Chinnaswamy Stadium                                                       3494
Arun Jaitley Stadium                                                        3356
Maharashtra Cricket Association Stadium, Pune                               3120
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                         3037
Sardar Patel Stadium, Motera                                                2893
SuperSport Park                                                             2866
Punjab Cricket Association IS Bindra Stadium, Mohali                        2574
Brabourne Stadium                                                           2469
Punjab Cricket Association IS Bindra Stadium                                2429
Saurashtra Cricket Association Stadium                                      2381
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur          2313
Himachal Pradesh Cricket Association Stadium                                2159
MA Chidambaram Stadium                                                      2130
Holkar Cricket Stadium                                                      1965
New Wanderers Stadium                                                       1940
Zayed Cricket Stadium, Abu Dhabi                                            1874
Barabati Stadium                                                            1695
St George's Park                                                            1677
JSCA International Stadium Complex                                          1671
Newlands                                                                    1539
Shaheed Veer Narayan Singh International Stadium                            1431
Himachal Pradesh Cricket Association Stadium, Dharamsala                    1298
Barsapara Cricket Stadium, Guwahati                                         1223
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh            1207
Nehru Stadium                                                               1155
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam           963
Green Park                                                                   921
Vidarbha Cricket Association Stadium, Jamtha                                 742
De Beers Diamond Oval                                                        726
Buffalo Park                                                                 715
OUTsurance Oval                                                              500
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh      248
Name: count, dtype: int64

--- team1 ---
team1
Chennai Super Kings            32526
Mumbai Indians                 31788
Royal Challengers Bangalore    31649
Kolkata Knight Riders          29946
Rajasthan Royals               25137
Sunrisers Hyderabad            22358
Kings XI Punjab                21848
Delhi Daredevils               19753
Delhi Capitals                 11447
Punjab Kings                    9733
Deccan Chargers                 9448
Lucknow Super Giants            7950
Gujarat Titans                  6446
Pune Warriors                   5483
Royal Challengers Bengaluru     4052
Gujarat Lions                   3784
Rising Pune Supergiants         1677
Rising Pune Supergiant          1617
Kochi Tuskers Kerala            1563
Name: count, dtype: int64

--- team2 ---
team2
Mumbai Indians                 34962
Kolkata Knight Riders          32118
Rajasthan Royals               30979
Chennai Super Kings            28080
Royal Challengers Bangalore    24914
Sunrisers Hyderabad            24436
Kings XI Punjab                23281
Delhi Daredevils               17758
Delhi Capitals                 14054
Deccan Chargers                 8625
Gujarat Titans                  8030
Punjab Kings                    7717
Lucknow Super Giants            6128
Pune Warriors                   5417
Gujarat Lions                   3327
Royal Challengers Bengaluru     3017
Rising Pune Supergiant          2211
Kochi Tuskers Kerala            1633
Rising Pune Supergiants         1518
Name: count, dtype: int64

--- toss_winner ---
toss_winner
Mumbai Indians                 36237
Chennai Super Kings            30729
Rajasthan Royals               30372
Kolkata Knight Riders          30361
Royal Challengers Bangalore    26701
Sunrisers Hyderabad            22363
Kings XI Punjab                20326
Delhi Daredevils               18548
Delhi Capitals                 14049
Deccan Chargers                10376
Punjab Kings                    8639
Gujarat Titans                  7072
Lucknow Super Giants            5894
Pune Warriors                   4798
Gujarat Lions                   3586
Royal Challengers Bengaluru     3520
Kochi Tuskers Kerala            1760
Rising Pune Supergiants         1503
Rising Pune Supergiant          1371
Name: count, dtype: int64

--- toss_decision ---
toss_decision
field    181679
bat       96526
Name: count, dtype: int64

--- winner ---
winner
Mumbai Indians                 36185
Chennai Super Kings            34371
Kolkata Knight Riders          31729
Rajasthan Royals               27466
Royal Challengers Bangalore    26801
Sunrisers Hyderabad            22183
Kings XI Punjab                20162
Delhi Daredevils               15709
Delhi Capitals                 12296
Gujarat Titans                  9000
Punjab Kings                    8158
Lucknow Super Giants            7430
Deccan Chargers                 7013
Royal Challengers Bengaluru     4244
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

--- result ---
result
wickets    148534
runs       129671
Name: count, dtype: int64

--- result_margin ---
result_margin
6      25255
7      21391
5      19756
8      14548
4      12945
       ...
75       211
146      211
76       204
112      189
86        17
Name: count, Length: 161, dtype: int64

--- player_of_match ---
player_of_match
AB de Villiers    6170
CH Gayle          5186
RG Sharma         5134
MS Dhoni          4384
DA Warner         4329
                  ...
WD Parnell         189
Ashwani Kumar      182
M Jansen           154
Suyash Sharma      147
DL Vettori         108
Name: count, Length: 308, dtype: int64

--- batting_team ---
batting_team
Mumbai Indians                 33323
Kolkata Knight Riders          30895
Chennai Super Kings            30395
Royal Challengers Bangalore    28205
Rajasthan Royals               27922
Sunrisers Hyderabad            23442
Kings XI Punjab                22646
Delhi Daredevils               18786
Delhi Capitals                 12615
Deccan Chargers                 9034
Punjab Kings                    8865
Gujarat Titans                  7331
Lucknow Super Giants            7144
Pune Warriors                   5443
Gujarat Lions                   3566
Royal Challengers Bengaluru     3531
Rising Pune Supergiant          1900
Kochi Tuskers Kerala            1582
Rising Pune Supergiants         1580
Name: count, dtype: int64

--- bowling_team ---
bowling_team
Mumbai Indians                 33427
Kolkata Knight Riders          31169
Chennai Super Kings            30211
Royal Challengers Bangalore    28358
Rajasthan Royals               28194
Sunrisers Hyderabad            23352
Kings XI Punjab                22483
Delhi Daredevils               18725
Delhi Capitals                 12886
Deccan Chargers                 9039
Punjab Kings                    8585
Gujarat Titans                  7145
Lucknow Super Giants            6934
Pune Warriors                   5457
Gujarat Lions                   3545
Royal Challengers Bengaluru     3538
Rising Pune Supergiant          1928
Rising Pune Supergiants         1615
Kochi Tuskers Kerala            1614
Name: count, dtype: int64

--- batter ---
batter
V Kohli           6702
S Dhawan          5483
RG Sharma         5475
DA Warner         4849
SK Raina          4177
                  ...
Abdul Basith         1
V Pratap Singh       1
Mayank Dagar         1
NJ Rimmington        1
SZ Mulani            1
Name: count, Length: 703, dtype: int64

--- bowler ---
bowler
R Ashwin         4868
SP Narine        4421
B Kumar          4378
RA Jadeja        4127
YS Chahal        3905
                 ...
SPD Smith           2
AC Gilchrist        1
Ishan Kishan        1
Atharva Taide       1
YBK Jaiswal         1
Name: count, Length: 550, dtype: int64

--- non_striker ---
non_striker
V Kohli            6671
S Dhawan           5942
RG Sharma          5586
DA Warner          4677
AM Rahane          4443
                   ...
KA Maharaj            1
Arshad Khan (2)       1
BW Hilfenhaus         1
Abdul Basith          1
TP Sudhindra          1
Name: count, Length: 692, dtype: int64

--- wicket_kind ---
wicket_kind
caught                   8665
bowled                   2345
run out                  1153
lbw                       853
caught and bowled         388
stumped                   376
hit wicket                 18
retired hurt               17
retired out                 5
obstructing the field       3
Name: count, dtype: int64

--- player_out ---
player_out
RG Sharma          237
V Kohli            219
S Dhawan           193
KD Karthik         184
RV Uthappa         180
                  ...
KM Asif              1
MP Breetzke          1
Musheer Khan         1
BKG Mendis           1
Sediqullah Atal      1
Name: count, Length: 655, dtype: int64

--- fielder ---
fielder
MS Dhoni           232
KD Karthik         199
AB de Villiers     141
V Kohli            135
RV Uthappa         133
                  ...
Suryansh Shedge      1
K Khejroliya         1
Sunny Singh          1
SB Dubey             1
R Goyal              1
Name: count, Length: 641, dtype: int64

In [5]:
cols = ['required_run_rate', 'target_score', 'wicket_kind', 'player_out', 'fielder']

for col in cols:
    print(f"\n{'='*50}")
    print(f"{col}")
    print(df[col].value_counts(dropna=False))

==================================================
required_run_rate
required_run_rate
 NaN      144302
 6.00       1294
 12.00      1158
 9.00       1076
 8.00        609
           ...
-1.29          1
 18.47         1
 22.53         1
 21.22         1
 20.38         1
Name: count, Length: 3075, dtype: int64

==================================================
target_score
target_score
NaN      144302
172.0      2548
163.0      2519
166.0      2470
165.0      2447
          ...
48.0         35
66.0         34
54.0         32
43.0         30
63.0         20
Name: count, Length: 176, dtype: int64

==================================================
wicket_kind
wicket_kind
NaN                      264382
caught                     8665
bowled                     2345
run out                    1153
lbw                         853
caught and bowled           388
stumped                     376
hit wicket                   18
retired hurt                 17
retired out                   5
obstructing the field         3
Name: count, dtype: int64

==================================================
player_out
player_out
NaN             264382
RG Sharma          237
V Kohli            219
S Dhawan           193
KD Karthik         184
                 ...
Mayank Dagar         1
XC Bartlett          1
KS Rathore           1
AA Noffke            1
DS Rathi             1
Name: count, Length: 656, dtype: int64

==================================================
fielder
fielder
NaN                 268192
MS Dhoni               232
KD Karthik             199
AB de Villiers         141
V Kohli                135
                     ...
M Siddharth              1
PVSN Raju                1
T Vijay                  1
BKG Mendis               1
T Kohler-Cadmore         1
Name: count, Length: 642, dtype: int64

### Missing Value Treatment

Missing values were analyzed based on the meaning of each variable.

- Null values in **`wicket_kind`**, **`player_out`**, and **`fielder`** were retained because they represent deliveries where no dismissal occurred.
- Similarly, **`target_score`** and **`required_run_rate`** were retained as missing where these metrics were not applicable.

Therefore, these null values were **not removed or replaced**, as they represent valid and meaningful missing values in the cricket dataset.

In [6]:
missing = df.isnull().sum().sort_values(ascending=False)

print(missing)

fielder              268192
player_out           264382
wicket_kind          264382
target_score         144302
required_run_rate    144302
city                  12397
winner                 4702
player_of_match         806
match_id                  0
toss_decision             0
toss_winner               0
result                    0
season                    0
team1                     0
team2                     0
date                      0
venue                     0
over                      0
bowling_team              0
batting_team              0
inning                    0
result_margin             0
ball                      0
bowler                    0
batter                    0
wickets_down              0
current_score             0
extras                    0
runs_scored               0
non_striker               0
current_run_rate          0
balls_remaining           0
wickets_remaining         0
dtype: int64

In [7]:
for col in df.columns:
    print(f"\n{'=' * 60}")
    print(f"        {col.upper()}")
    print(f"{'=' * 60}")
    print("Unique values:", df[col].unique())
    print("Missing values:", df[col].isnull().sum())

============================================================
        MATCH_ID
============================================================
Unique values: [ 335982  335983  335984 ... 1473510 1473511 1485779]
Missing values: 0

============================================================
        SEASON
============================================================
Unique values: ['2007/08' '2009' '2009/10' '2011' 2011 2012 2013 2014 2015 2016 2017 2018
 '2018' '2019' '2020/21' '2021' 2021 2022 2023 2024 2025]
Missing values: 0

============================================================
        DATE
============================================================
Unique values: ['4/18/2008' '4/19/2008' '4/20/2008' '4/21/2008' '4/22/2008' '4/23/2008'
 '4/24/2008' '4/25/2008' '4/26/2008' '4/27/2008' '4/28/2008' '4/29/2008'
 '4/30/2008' '5/1/2008' '5/2/2008' '5/25/2008' '5/3/2008' '5/4/2008'
 '5/5/2008' '5/6/2008' '5/7/2008' '5/8/2008' '5/9/2008' '5/28/2008'
 '5/10/2008' '5/11/2008' '5/12/2008' '5/13/2008' '5/14/2008' '5/15/2008'
 '5/16/2008' '5/17/2008' '5/18/2008' '5/19/2008' '5/20/2008' '5/21/2008'
 '5/23/2008' '5/24/2008' '5/26/2008' '5/27/2008' '5/30/2008' '5/31/2008'
 '6/1/2008' '4/18/2009' '4/19/2009' '4/20/2009' '4/21/2009' '4/22/2009'
 '4/23/2009' '4/24/2009' '4/25/2009' '4/26/2009' '4/27/2009' '4/28/2009'
 '4/29/2009' '4/30/2009' '5/1/2009' '5/2/2009' '5/3/2009' '5/4/2009'
 '5/5/2009' '5/6/2009' '5/7/2009' '5/8/2009' '5/9/2009' '5/10/2009'
 '5/11/2009' '5/12/2009' '5/13/2009' '5/14/2009' '5/15/2009' '5/16/2009'
 '5/17/2009' '5/18/2009' '5/19/2009' '5/20/2009' '5/21/2009' '5/22/2009'
 '5/23/2009' '5/24/2009' '3/12/2010' '3/13/2010' '3/14/2010' '3/15/2010'
 '3/16/2010' '3/17/2010' '3/18/2010' '3/19/2010' '3/20/2010' '3/21/2010'
 '3/22/2010' '3/23/2010' '3/24/2010' '3/25/2010' '3/26/2010' '3/27/2010'
 '3/28/2010' '3/29/2010' '3/30/2010' '3/31/2010' '4/1/2010' '4/2/2010'
 '4/3/2010' '4/4/2010' '4/5/2010' '4/6/2010' '4/7/2010' '4/8/2010'
 '4/9/2010' '4/10/2010' '4/11/2010' '4/12/2010' '4/13/2010' '4/14/2010'
 '4/15/2010' '4/16/2010' '4/17/2010' '4/18/2010' '4/19/2010' '4/21/2010'
 '4/22/2010' '4/24/2010' '4/25/2010' '4/8/2011' '4/9/2011' '4/10/2011'
 '4/11/2011' '4/12/2011' '4/13/2011' '4/14/2011' '4/15/2011' '4/16/2011'
 '4/17/2011' '4/18/2011' '4/19/2011' '4/20/2011' '4/21/2011' '4/22/2011'
 '4/23/2011' '4/24/2011' '4/25/2011' '4/26/2011' '4/27/2011' '4/28/2011'
 '4/29/2011' '4/30/2011' '5/1/2011' '5/2/2011' '5/3/2011' '5/4/2011'
 '5/5/2011' '5/6/2011' '5/7/2011' '5/8/2011' '5/9/2011' '5/10/2011'
 '5/11/2011' '5/12/2011' '5/13/2011' '5/14/2011' '5/15/2011' '5/16/2011'
 '5/17/2011' '5/18/2011' '5/19/2011' '5/20/2011' '5/21/2011' '5/22/2011'
 '5/24/2011' '5/25/2011' '5/27/2011' '5/28/2011' '4/4/2012' '4/5/2012'
 '4/6/2012' '4/7/2012' '4/8/2012' '4/9/2012' '4/10/2012' '4/11/2012'
 '4/12/2012' '4/13/2012' '4/19/2012' '4/14/2012' '4/15/2012' '4/16/2012'
 '4/17/2012' '4/18/2012' '5/10/2012' '4/20/2012' '4/21/2012' '4/22/2012'
 '4/23/2012' '4/24/2012' '4/25/2012' '4/26/2012' '4/27/2012' '4/28/2012'
 '4/29/2012' '4/30/2012' '5/1/2012' '5/2/2012' '5/3/2012' '5/4/2012'
 '5/5/2012' '5/6/2012' '5/7/2012' '5/8/2012' '5/9/2012' '5/11/2012'
 '5/12/2012' '5/13/2012' '5/14/2012' '5/15/2012' '5/16/2012' '5/17/2012'
 '5/18/2012' '5/19/2012' '5/20/2012' '5/22/2012' '5/23/2012' '5/25/2012'
 '5/27/2012' '4/3/2013' '4/4/2013' '4/5/2013' '4/6/2013' '4/7/2013'
 '4/8/2013' '4/9/2013' '4/10/2013' '4/11/2013' '4/12/2013' '4/13/2013'
 '4/14/2013' '4/15/2013' '4/16/2013' '4/17/2013' '4/18/2013' '4/19/2013'
 '4/20/2013' '4/21/2013' '4/22/2013' '4/23/2013' '5/16/2013' '4/24/2013'
 '4/25/2013' '4/26/2013' '4/27/2013' '4/28/2013' '4/29/2013' '4/30/2013'
 '5/1/2013' '5/2/2013' '5/3/2013' '5/4/2013' '5/14/2013' '5/5/2013'
 '5/7/2013' '5/8/2013' '5/9/2013' '5/10/2013' '5/11/2013' '5/12/2013'
 '5/13/2013' '5/15/2013' '5/6/2013' '5/17/2013' '5/18/2013' '5/19/2013'
 '5/21/2013' '5/22/2013' '5/24/2013' '5/26/2013' '4/16/2014' '4/17/2014'
 '4/18/2014' '4/19/2014' '4/20/2014' '4/21/2014' '4/22/2014' '4/23/2014'
 '4/24/2014' '4/25/2014' '4/26/2014' '4/27/2014' '4/28/2014' '4/29/2014'
 '4/30/2014' '5/2/2014' '5/3/2014' '5/4/2014' '5/5/2014' '5/6/2014'
 '5/7/2014' '5/8/2014' '5/9/2014' '5/10/2014' '5/11/2014' '5/12/2014'
 '5/13/2014' '5/14/2014' '5/15/2014' '5/18/2014' '5/19/2014' '5/20/2014'
 '5/21/2014' '5/22/2014' '5/23/2014' '5/24/2014' '5/25/2014' '5/27/2014'
 '5/28/2014' '5/30/2014' '6/1/2014' '4/8/2015' '4/9/2015' '4/10/2015'
 '4/11/2015' '4/12/2015' '4/13/2015' '4/14/2015' '4/30/2015' '4/15/2015'
 '4/16/2015' '4/17/2015' '4/18/2015' '4/19/2015' '4/20/2015' '4/21/2015'
 '4/22/2015' '4/23/2015' '4/24/2015' '4/25/2015' '4/26/2015' '4/27/2015'
 '5/7/2015' '4/29/2015' '4/28/2015' '5/1/2015' '5/2/2015' '5/3/2015'
 '5/4/2015' '5/5/2015' '5/6/2015' '5/8/2015' '5/9/2015' '5/10/2015'
 '5/11/2015' '5/12/2015' '5/13/2015' '5/14/2015' '5/15/2015' '5/16/2015'
 '5/17/2015' '5/19/2015' '5/20/2015' '5/22/2015' '5/24/2015' '4/9/2016'
 '4/10/2016' '4/11/2016' '4/12/2016' '4/13/2016' '4/14/2016' '4/15/2016'
 '4/16/2016' '4/17/2016' '4/18/2016' '4/19/2016' '4/20/2016' '4/21/2016'
 '4/22/2016' '4/23/2016' '4/24/2016' '4/25/2016' '4/26/2016' '4/27/2016'
 '4/28/2016' '4/29/2016' '4/30/2016' '5/1/2016' '5/2/2016' '5/3/2016'
 '5/4/2016' '5/5/2016' '5/6/2016' '5/7/2016' '5/8/2016' '5/9/2016'
 '5/10/2016' '5/11/2016' '5/12/2016' '5/13/2016' '5/14/2016' '5/15/2016'
 '5/16/2016' '5/17/2016' '5/18/2016' '5/19/2016' '5/20/2016' '5/21/2016'
 '5/22/2016' '5/24/2016' '5/25/2016' '5/27/2016' '5/29/2016' '4/5/2017'
 '4/6/2017' '4/7/2017' '4/8/2017' '4/9/2017' '4/10/2017' '4/11/2017'
 '4/12/2017' '4/13/2017' '4/14/2017' '4/15/2017' '4/16/2017' '4/17/2017'
 '4/18/2017' '4/19/2017' '4/20/2017' '4/21/2017' '4/22/2017' '4/23/2017'
 '4/24/2017' '4/26/2017' '4/27/2017' '4/28/2017' '4/29/2017' '4/30/2017'
 '5/1/2017' '5/2/2017' '5/3/2017' '5/4/2017' '5/5/2017' '5/6/2017'
 '5/7/2017' '5/8/2017' '5/9/2017' '5/10/2017' '5/11/2017' '5/12/2017'
 '5/13/2017' '5/14/2017' '5/16/2017' '5/17/2017' '5/19/2017' '5/21/2017'
 '4/7/2018' '4/8/2018' '4/9/2018' '4/10/2018' '4/11/2018' '4/12/2018'
 '4/13/2018' '4/14/2018' '4/15/2018' '4/16/2018' '4/17/2018' '4/18/2018'
 '4/19/2018' '4/20/2018' '4/21/2018' '4/22/2018' '4/23/2018' '4/24/2018'
 '4/25/2018' '4/26/2018' '4/27/2018' '4/28/2018' '4/29/2018' '4/30/2018'
 '5/1/2018' '5/2/2018' '5/3/2018' '5/4/2018' '5/5/2018' '5/6/2018'
 '5/7/2018' '5/8/2018' '5/9/2018' '5/10/2018' '5/11/2018' '5/12/2018'
 '5/13/2018' '5/14/2018' '5/15/2018' '5/16/2018' '5/17/2018' '5/18/2018'
 '5/19/2018' '5/20/2018' '5/22/2018' '5/23/2018' '5/25/2018' '5/27/2018'
 '3/23/2019' '3/24/2019' '3/25/2019' '3/26/2019' '3/27/2019' '3/28/2019'
 '3/29/2019' '3/30/2019' '3/31/2019' '4/1/2019' '4/2/2019' '4/3/2019'
 '4/4/2019' '4/5/2019' '4/6/2019' '4/7/2019' '4/8/2019' '4/9/2019'
 '4/10/2019' '4/11/2019' '4/12/2019' '4/13/2019' '4/14/2019' '4/15/2019'
 '4/16/2019' '4/17/2019' '4/18/2019' '4/19/2019' '4/20/2019' '4/21/2019'
 '4/22/2019' '4/23/2019' '4/24/2019' '4/25/2019' '4/26/2019' '4/27/2019'
 '4/28/2019' '4/29/2019' '4/30/2019' '5/1/2019' '5/2/2019' '5/3/2019'
 '5/4/2019' '5/5/2019' '5/7/2019' '5/8/2019' '5/10/2019' '5/12/2019'
 '9/19/2020' '9/20/2020' '10/21/2020' '11/3/2020' '9/22/2020' '10/24/2020'
 '10/28/2020' '10/9/2020' '10/7/2020' '10/31/2020' '10/1/2020' '9/30/2020'
 '11/2/2020' '11/1/2020' '10/11/2020' '9/23/2020' '10/17/2020' '9/24/2020'
 '10/6/2020' '10/18/2020' '10/4/2020' '10/3/2020' '10/2/2020' '10/22/2020'
 '10/5/2020' '10/26/2020' '10/23/2020' '10/10/2020' '10/27/2020'
 '10/16/2020' '9/27/2020' '10/13/2020' '10/15/2020' '9/29/2020'
 '10/19/2020' '9/21/2020' '10/29/2020' '10/30/2020' '9/25/2020'
 '10/12/2020' '10/25/2020' '10/8/2020' '10/14/2020' '9/26/2020'
 '10/20/2020' '9/28/2020' '11/5/2020' '11/6/2020' '11/8/2020' '11/10/2020'
 '4/9/2021' '4/10/2021' '4/11/2021' '4/12/2021' '4/13/2021' '4/14/2021'
 '4/15/2021' '4/16/2021' '4/17/2021' '4/18/2021' '4/19/2021' '4/20/2021'
 '4/21/2021' '4/22/2021' '4/23/2021' '4/24/2021' '4/25/2021' '4/26/2021'
 '4/27/2021' '4/28/2021' '4/29/2021' '4/30/2021' '5/1/2021' '5/2/2021'
 '9/20/2021' '10/8/2021' '10/2/2021' '10/3/2021' '9/30/2021' '9/28/2021'
 '10/5/2021' '10/7/2021' '10/6/2021' '9/23/2021' '9/25/2021' '9/26/2021'
 '9/27/2021' '10/1/2021' '9/29/2021' '9/19/2021' '9/22/2021' '10/4/2021'
 '9/21/2021' '9/24/2021' '10/10/2021' '10/11/2021' '10/13/2021'
 '10/15/2021' '3/26/2022' '3/27/2022' '3/28/2022' '3/29/2022' '3/30/2022'
 '3/31/2022' '4/1/2022' '4/2/2022' '4/3/2022' '4/4/2022' '4/5/2022'
 '4/6/2022' '4/7/2022' '4/8/2022' '4/9/2022' '4/10/2022' '4/11/2022'
 '4/12/2022' '4/13/2022' '4/14/2022' '4/15/2022' '4/16/2022' '4/17/2022'
 '4/18/2022' '4/19/2022' '4/20/2022' '4/21/2022' '4/22/2022' '4/23/2022'
 '4/24/2022' '4/25/2022' '4/26/2022' '4/27/2022' '4/28/2022' '4/29/2022'
 '4/30/2022' '5/1/2022' '5/2/2022' '5/3/2022' '5/4/2022' '5/5/2022'
 '5/6/2022' '5/7/2022' '5/8/2022' '5/9/2022' '5/10/2022' '5/11/2022'
 '5/12/2022' '5/13/2022' '5/14/2022' '5/15/2022' '5/16/2022' '5/17/2022'
 '5/18/2022' '5/19/2022' '5/20/2022' '5/21/2022' '5/22/2022' '5/24/2022'
 '5/25/2022' '5/27/2022' '5/29/2022' '3/31/2023' '4/1/2023' '4/2/2023'
 '4/3/2023' '4/4/2023' '4/5/2023' '4/6/2023' '4/7/2023' '4/8/2023'
 '4/9/2023' '4/10/2023' '4/11/2023' '4/12/2023' '4/13/2023' '4/14/2023'
 '4/15/2023' '4/16/2023' '4/17/2023' '4/18/2023' '4/19/2023' '4/20/2023'
 '4/21/2023' '4/22/2023' '4/23/2023' '4/24/2023' '4/25/2023' '4/26/2023'
 '4/27/2023' '4/28/2023' '4/29/2023' '4/30/2023' '5/1/2023' '5/2/2023'
 '5/3/2023' '5/4/2023' '5/5/2023' '5/6/2023' '5/7/2023' '5/8/2023'
 '5/9/2023' '5/10/2023' '5/11/2023' '5/12/2023' '5/13/2023' '5/14/2023'
 '5/15/2023' '5/16/2023' '5/17/2023' '5/18/2023' '5/19/2023' '5/20/2023'
 '5/21/2023' '5/23/2023' '5/24/2023' '5/26/2023' '5/29/2023' '3/22/2024'
 '3/23/2024' '3/24/2024' '3/25/2024' '3/26/2024' '3/27/2024' '3/28/2024'
 '3/29/2024' '3/30/2024' '3/31/2024' '4/1/2024' '4/2/2024' '4/3/2024'
 '4/4/2024' '4/5/2024' '4/6/2024' '4/7/2024' '4/8/2024' '4/9/2024'
 '4/10/2024' '4/11/2024' '4/12/2024' '4/13/2024' '4/14/2024' '4/15/2024'
 '4/16/2024' '4/17/2024' '4/18/2024' '4/19/2024' '4/20/2024' '4/21/2024'
 '4/22/2024' '4/23/2024' '4/24/2024' '4/25/2024' '4/26/2024' '4/27/2024'
 '4/28/2024' '4/29/2024' '4/30/2024' '5/1/2024' '5/2/2024' '5/3/2024'
 '5/4/2024' '5/5/2024' '5/6/2024' '5/7/2024' '5/8/2024' '5/9/2024'
 '5/10/2024' '5/11/2024' '5/12/2024' '5/14/2024' '5/15/2024' '5/17/2024'
 '5/18/2024' '5/19/2024' '5/21/2024' '5/22/2024' '5/24/2024' '5/26/2024'
 '3/22/2025' '3/23/2025' '3/24/2025' '3/25/2025' '3/26/2025' '3/27/2025'
 '3/28/2025' '3/29/2025' '3/30/2025' '3/31/2025' '4/1/2025' '4/2/2025'
 '4/3/2025' '4/4/2025' '4/5/2025' '4/8/2025' '4/6/2025' '4/7/2025'
 '4/9/2025' '4/10/2025' '4/11/2025' '4/12/2025' '4/13/2025' '4/14/2025'
 '4/15/2025' '4/16/2025' '4/17/2025' '4/18/2025' '4/19/2025' '4/20/2025'
 '4/21/2025' '4/22/2025' '4/23/2025' '4/24/2025' '4/25/2025' '4/26/2025'
 '4/27/2025' '4/28/2025' '4/29/2025' '4/30/2025' '5/1/2025' '5/2/2025'
 '5/3/2025' '5/4/2025' '5/5/2025' '5/6/2025' '5/7/2025' '5/8/2025'
 '5/18/2025' '5/19/2025' '5/20/2025' '5/21/2025' '5/22/2025' '5/23/2025'
 '5/25/2025' '5/26/2025' '5/27/2025' '5/29/2025' '5/30/2025' '6/1/2025'
 '6/3/2025' '5/24/2025']
Missing values: 0

============================================================
        CITY
============================================================
Unique values: ['Bangalore' 'Chandigarh' 'Delhi' 'Mumbai' 'Kolkata' 'Jaipur' 'Hyderabad'
 'Chennai' 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur'
 'Dharamsala' 'Kochi' 'Indore' 'Visakhapatnam' 'Pune' 'Raipur' 'Ranchi'
 'Abu Dhabi' nan 'Rajkot' 'Kanpur' 'Bengaluru' 'Sharjah' 'Dubai'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Mohali' 'New Chandigarh']
Missing values: 12397

============================================================
        VENUE
============================================================
Unique values: ['M Chinnaswamy Stadium' 'Punjab Cricket Association Stadium, Mohali'
 'Feroz Shah Kotla' 'Wankhede Stadium' 'Eden Gardens'
 'Sawai Mansingh Stadium' 'Rajiv Gandhi International Stadium, Uppal'
 'MA Chidambaram Stadium, Chepauk' 'Dr DY Patil Sports Academy' 'Newlands'
 "St George's Park" 'Kingsmead' 'SuperSport Park' 'Buffalo Park'
 'New Wanderers Stadium' 'De Beers Diamond Oval' 'OUTsurance Oval'
 'Brabourne Stadium' 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Brabourne Stadium, Mumbai'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Holkar Cricket Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Subrata Roy Sahara Stadium' 'Maharashtra Cricket Association Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex' 'Sheikh Zayed Stadium'
 'Sharjah Cricket Stadium' 'Dubai International Cricket Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'Saurashtra Cricket Association Stadium' 'Green Park'
 'M.Chinnaswamy Stadium' 'Punjab Cricket Association IS Bindra Stadium'
 'Rajiv Gandhi International Stadium' 'MA Chidambaram Stadium'
 'Arun Jaitley Stadium' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Wankhede Stadium, Mumbai' 'Narendra Modi Stadium, Ahmedabad'
 'Arun Jaitley Stadium, Delhi' 'Zayed Cricket Stadium, Abu Dhabi'
 'Dr DY Patil Sports Academy, Mumbai'
 'Maharashtra Cricket Association Stadium, Pune' 'Eden Gardens, Kolkata'
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'M Chinnaswamy Stadium, Bengaluru' 'Barsapara Cricket Stadium, Guwahati'
 'Sawai Mansingh Stadium, Jaipur'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala'
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam'
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh']
Missing values: 0

============================================================
        TEAM1
============================================================
Unique values: ['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']
Missing values: 0

============================================================
        TEAM2
============================================================
Unique values: ['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
Missing values: 0

============================================================
        TOSS_WINNER
============================================================
Unique values: ['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Gujarat Titans' 'Lucknow Super Giants'
 'Royal Challengers Bengaluru']
Missing values: 0

============================================================
        TOSS_DECISION
============================================================
Unique values: ['field' 'bat']
Missing values: 0

============================================================
        WINNER
============================================================
Unique values: ['Kolkata Knight Riders' 'Chennai Super Kings' 'Delhi Daredevils'
 'Royal Challengers Bangalore' 'Rajasthan Royals' 'Kings XI Punjab'
 'Deccan Chargers' 'Mumbai Indians' nan 'Pune Warriors'
 'Kochi Tuskers Kerala' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
Missing values: 4702

============================================================
        RESULT
============================================================
Unique values: ['runs' 'wickets']
Missing values: 0

============================================================
        RESULT_MARGIN
============================================================
Unique values: ['140' '33' '9' '5' '6' '3' '66' '7' '10' '4' '13' '45' '8' '29' '18' '23'
 '41' '12' '65' '25' '1' '14' '105' '19' '75' '92' '11' '24' 'undefined'
 '27' '38' '78' '16' '53' '2' '31' '55' '98' '34' '36' '39' '17' 17 41 40
 4 5 67 24 6 23 63 8 37 2 9 14 7 13 39 57 11 35 38 22 33 21 3 16 48 29 25
 55 '26' '20' '21' '85' '32' '63' '76' '111' '82' '43' '58' '28' '74' '22'
 '42' '59' '46' '37' '47' '35' '86' '44' '48' '87' 86 130 58 15 60 65 77
 46 30 50 93 72 '15' '62' '30' '97' '138' '71' '144' '80' '51' '61' '146'
 10 20 1 19 71 64 31 102 34 '118' '40' '49' '57' '88' '60' '69' '54' 12 18
 36 75 91 52 62 54 81 '56' '112' '77' '81' 28 106 78 98 47 27 44 '50'
 '100' '83' '110']
Missing values: 0

============================================================
        PLAYER_OF_MATCH
============================================================
Unique values: ['BB McCullum' 'MEK Hussey' 'MF Maharoof' 'MV Boucher' 'DJ Hussey'
 'SR Watson' 'V Sehwag' 'ML Hayden' 'YK Pathan' 'KC Sangakkara' 'JDP Oram'
 'AC Gilchrist' 'SM Katich' 'MS Dhoni' 'ST Jayasuriya' 'GD McGrath'
 'SE Marsh' 'SA Asnodkar' 'R Vinay Kumar' 'IK Pathan' 'SM Pollock'
 'Sohail Tanvir' 'S Sreesanth' 'A Nehra' 'SC Ganguly' 'CRD Fernando'
 'L Balaji' 'Shoaib Akhtar' 'A Mishra' 'DPMD Jayawardene' 'GC Smith'
 'DJ Bravo' 'M Ntini' 'SP Goswami' 'A Kumble' 'KD Karthik' 'JA Morkel'
 'P Kumar' 'Umar Gul' 'SK Raina' 'SR Tendulkar' 'R Dravid' 'DL Vettori'
 'RP Singh' 'M Muralitharan' 'CH Gayle' 'AB de Villiers' 'RS Bopara'
 'PP Ojha' 'TM Dilshan' 'HH Gibbs' 'DP Nannes' 'JP Duminy' 'Yuvraj Singh'
 'SB Jakati' 'JH Kallis' 'G Gambhir' 'RG Sharma' 'A Singh' 'S Badrinath'
 'DR Smith' 'LRPL Taylor' 'Harbhajan Singh' 'R Bhatia' 'SK Warne' 'B Lee'
 'BJ Hodge' 'LR Shukla' 'MK Pandey' 'AD Mathews' 'MK Tiwary' 'WPUJC Vaas'
 'A Symonds' 'AA Jhunjhunwala' 'J Theron' 'RV Uthappa' 'AC Voges'
 'KM Jadhav' 'NV Ojha' 'DA Warner' 'SL Malinga' 'M Vijay' 'KP Pietersen'
 'AT Rayudu' 'PD Collingwood' 'MJ Lumb' 'TL Suman' 'RJ Harris' 'PP Chawla'
 'Harmeet Singh' 'KA Pollard' 'R Ashwin' 'R McLaren' 'JD Unadkat'
 'M Kartik' 'DE Bollinger' 'S Anirudha' 'SK Trivedi' 'SB Wagh'
 'PC Valthaty' 'MD Mishra' 'DW Steyn' 'S Sohal' 'MM Patel' 'V Kohli'
 'I Sharma' 'J Botha' 'Iqbal Abdulla' 'P Parameswaran' 'R Sharma'
 'MR Marsh' 'BA Bhatt' 'S Aravind' 'WP Saha' 'S Dhawan' nan 'JEC Franklin'
 'RE Levi' 'SPD Smith' 'AM Rahane' 'RA Jadeja' 'MN Samuels' 'M Morkel'
 'F du Plessis' 'AD Mascarenhas' 'Shakib Al Hasan' 'JD Ryder' 'SP Narine'
 'S Nadeem' 'KMDN Kulasekara' 'CL White' 'Mandeep Singh' 'P Negi'
 'Azhar Mahmood' 'BW Hilfenhaus' 'A Chandila' 'UT Yadav' 'MS Bisla'
 'M Vohra' 'GH Vihari' 'AJ Finch' 'JP Faulkner' 'MS Gony' 'DA Miller'
 'SV Samson' 'DJG Sammy' 'MG Johnson' 'KK Cooper' 'PA Patel' 'AP Tare'
 'LJ Wright' 'YS Chahal' 'GJ Maxwell' 'CA Lynn' 'MM Sharma' 'PV Tambe'
 'Sandeep Sharma' 'B Kumar' 'CJ Anderson' 'KK Nair' 'AR Patel'
 'LMP Simmons' 'DJ Hooda' 'GJ Bailey' 'AD Russell' 'MA Agarwal' 'SS Iyer'

In [8]:
missing_summary = pd.DataFrame({
    'Column': df.columns,
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary

                              Column  Missing Values  Missing Percentage
match_id                    match_id               0                0.00
season                        season               0                0.00
date                            date               0                0.00
city                            city           12397                4.46
venue                          venue               0                0.00
team1                          team1               0                0.00
team2                          team2               0                0.00
toss_winner              toss_winner               0                0.00
toss_decision          toss_decision               0                0.00
winner                        winner            4702                1.69
result                        result               0                0.00
result_margin          result_margin               0                0.00
player_of_match      player_of_match             806                0.29
inning                        inning               0                0.00
batting_team            batting_team               0                0.00
bowling_team            bowling_team               0                0.00
over                            over               0                0.00
ball                            ball               0                0.00
batter                        batter               0                0.00
bowler                        bowler               0                0.00
non_striker              non_striker               0                0.00
runs_scored              runs_scored               0                0.00
extras                        extras               0                0.00
current_score          current_score               0                0.00
wickets_down            wickets_down               0                0.00
balls_remaining      balls_remaining               0                0.00
wickets_remaining  wickets_remaining               0                0.00
current_run_rate    current_run_rate               0                0.00
required_run_rate  required_run_rate          144302               51.87
target_score            target_score          144302               51.87
wicket_kind              wicket_kind          264382               95.03
player_out                player_out          264382               95.03
fielder                      fielder          268192               96.40

### Missing Value Analysis

The columns **`wicket_kind`**, **`player_out`**, and **`fielder`** contain a high percentage of missing values (95.03%, 95.03%, and 96.40%, respectively). These missing values were retained because they are expected in deliveries where no relevant dismissal event occurred. Therefore, they were not treated as erroneous missing data.

In [9]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium    8080
Sharjah Cricket Stadium                4317
Name: count, dtype: int64

In [10]:
## Treating City column missing values
df.loc[
    (df['city'].isnull()) & 
    (df['venue'] == 'Dubai International Cricket Stadium'),
    'city'
] = 'Dubai'

df.loc[
    (df['city'].isnull()) & 
    (df['venue'] == 'Sharjah Cricket Stadium'),
    'city'
] = 'Sharjah'

In [11]:
df['city'].isnull().sum()

np.int64(0)

### Winner column

In [12]:
df[df['winner'].isnull()]['result'].value_counts(dropna=False)

result
wickets    4702
Name: count, dtype: int64

In [13]:
df.columns.tolist()

['match_id',
 'season',
 'date',
 'city',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'player_of_match',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batter',
 'bowler',
 'non_striker',
 'runs_scored',
 'extras',
 'current_score',
 'wickets_down',
 'balls_remaining',
 'wickets_remaining',
 'current_run_rate',
 'required_run_rate',
 'target_score',
 'wicket_kind',
 'player_out',
 'fielder']

In [14]:
df[df['winner'].isnull()][['match_id', 'team1', 'team2', 'result']].drop_duplicates()

,match_id,team1,team2,result
15161,392190,Kolkata Knight Riders,Rajasthan Royals,wickets
30707,419121,Chennai Super Kings,Kings XI Punjab,wickets
57068,501265,Delhi Daredevils,Pune Warriors,wickets
77794,598004,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets
80965,598017,Royal Challengers Bangalore,Delhi Daredevils,wickets
98800,729315,Kolkata Knight Riders,Rajasthan Royals,wickets
113250,829741,Rajasthan Royals,Kings XI Punjab,wickets
115599,829763,Royal Challengers Bangalore,Rajasthan Royals,wickets
121177,829813,Royal Challengers Bangalore,Delhi Daredevils,wickets
144440,1082625,Gujarat Lions,Mumbai Indians,wickets
166931,1175365,Kolkata Knight Riders,Delhi Capitals,wickets
176392,1178424,Royal Challengers Bangalore,Rajasthan Royals,wickets
176666,1178426,Mumbai Indians,Sunrisers Hyderabad,wickets
179302,1216493,Delhi Capitals,Kings XI Punjab,wickets
183889,1216512,Kolkata Knight Riders,Sunrisers Hyderabad,wickets
185115,1216517,Mumbai Indians,Kings XI Punjab,wickets
192378,1216547,Royal Challengers Bangalore,Mumbai Indians,wickets
198245,1254077,Delhi Capitals,Sunrisers Hyderabad,wickets
236750,1359519,Lucknow Super Giants,Chennai Super Kings,wickets
268306,1473469,Delhi Capitals,Rajasthan Royals,wickets
271126,1473481,Punjab Kings,Kolkata Knight Riders,wickets
273705,1473492,Delhi Capitals,Sunrisers Hyderabad,wickets
274316,1473495,Punjab Kings,Delhi Capitals,wickets

In [15]:
df[df['winner'].isnull()][
    ['match_id', 'inning', 'batting_team', 'result']
].drop_duplicates().sort_values(['match_id', 'inning'])

        match_id  inning           batting_team   result
15161     392190       1       Rajasthan Royals  wickets
15287     392190       2  Kolkata Knight Riders  wickets
15417     392190       3  Kolkata Knight Riders  wickets
15424     392190       4       Rajasthan Royals  wickets
30707     419121       1        Kings XI Punjab  wickets
...          ...     ...                    ...      ...
268564   1473469       4         Delhi Capitals  wickets
271126   1473481       1           Punjab Kings  wickets
271249   1473481       2  Kolkata Knight Riders  wickets
273705   1473492       1         Delhi Capitals  wickets
274316   1473495       1           Punjab Kings  wickets

[73 rows x 4 columns]

In [16]:
last_inning_team = (
    df.groupby('match_id')
      .apply(lambda x: x.loc[x['inning'].idxmax(), 'batting_team'])
)

known_winner = (
    df[['match_id', 'winner']]
      .dropna(subset=['winner'])
      .drop_duplicates('match_id')
)

check = known_winner.copy()

check['last_inning_team'] = check['match_id'].map(last_inning_team)

check['matches'] = check['winner'] == check['last_inning_team']

check['matches'].value_counts()

C:\Users\admin\AppData\Local\Temp\ipykernel_8376\3374671757.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.loc[x['inning'].idxmax(), 'batting_team'])

matches
True     621
False    525
Name: count, dtype: int64

In [17]:
match_info = df[['match_id', 'winner', 'result']].drop_duplicates('match_id')

second_inning_team = (
    df[df['inning'] == 2]
    .groupby('match_id')['batting_team']
    .first()
)

check = match_info[
    (match_info['result'] == 'wickets') &
    (match_info['winner'].notna())
].copy()

check['second_inning_team'] = check['match_id'].map(second_inning_team)

check['winner_matches'] = (
    check['winner'] == check['second_inning_team']
)

check['winner_matches'].value_counts()

winner_matches
True    615
Name: count, dtype: int64

In [18]:
second_inning_team = (
    df[df['inning'] == 2]
    .groupby('match_id')['batting_team']
    .first()
)

df['winner'] = df['winner'].fillna(
    df['match_id'].map(second_inning_team)
)

In [19]:
df['winner'].isnull().sum()

np.int64(495)

In [20]:
remaining_winner = df[df['winner'].isnull()][
    ['match_id', 'inning', 'batting_team', 'team1', 'team2', 'result']
].drop_duplicates().sort_values(['match_id', 'inning'])

remaining_winner

,match_id,inning,batting_team,team1,team2,result
57068,501265,1,Delhi Daredevils,Delhi Daredevils,Pune Warriors,wickets
115599,829763,1,Royal Challengers Bangalore,Royal Challengers Bangalore,Rajasthan Royals,wickets
236750,1359519,1,Lucknow Super Giants,Lucknow Super Giants,Chennai Super Kings,wickets
273705,1473492,1,Delhi Capitals,Delhi Capitals,Sunrisers Hyderabad,wickets
274316,1473495,1,Punjab Kings,Punjab Kings,Delhi Capitals,wickets

In [21]:
df[df['winner'].isnull()]['inning'].value_counts()

inning
1    495
Name: count, dtype: int64

In [22]:
# 1. Check remaining missing values
print("Missing winner values:", df['winner'].isnull().sum())

# 2. Check that each match has at most one unique winner
winner_per_match = df.groupby('match_id')['winner'].nunique(dropna=True)
print("Maximum unique winners in a match:", winner_per_match.max())

# 3. Check whether winner is one of the two teams
valid_winner = (
    df['winner'].isna() |
    (df['winner'] == df['team1']) |
    (df['winner'] == df['team2'])
)

print("Invalid winner records:", (~valid_winner).sum())

# 4. Check filled winners against second innings
second_inning_team = (
    df[df['inning'] == 2]
    .groupby('match_id')['batting_team']
    .first()
)

wicket_matches = df[
    (df['result'] == 'wickets') &
    (df['winner'].notna())
].drop_duplicates('match_id').copy()

wicket_matches['second_inning_team'] = (
    wicket_matches['match_id'].map(second_inning_team)
)

wicket_matches['verified'] = (
    wicket_matches['winner'] == wicket_matches['second_inning_team']
)

print("Wicket-result matches verified:")
print(wicket_matches['verified'].value_counts(dropna=False))

Missing winner values: 495
Maximum unique winners in a match: 1
Invalid winner records: 0
Wicket-result matches verified:
verified
True    633
Name: count, dtype: int64

### Winner Column – Missing Value Treatment

The **`winner`** column was analyzed using **`match_id`**, **`inning`**, and **`batting_team`**.

Missing winner values were filled where the second-innings batting team could reliably determine the match winner. This resulted in **4,207 values being filled**.

A total of **495 values** remained missing because only first-innings information was available, making it impossible to determine the winner reliably. These values were retained as `NaN` rather than making assumptions.

The cleaned column was verified to ensure that each match has at most one winner and that all available winners belong to either **`team1`** or **`team2`**.

### Player of Match

In [23]:
df[df['player_of_match'].isnull()]['result'].value_counts(dropna=False)

result
wickets    806
Name: count, dtype: int64

In [24]:
pom_check = df.groupby('match_id')['player_of_match'].nunique(dropna=True)

print("Matches with player_of_match available:", (pom_check > 0).sum())
print("Matches with player_of_match completely missing:", (pom_check == 0).sum())
print("Maximum unique player_of_match per match:", pom_check.max())

Matches with player_of_match available: 1161
Matches with player_of_match completely missing: 8
Maximum unique player_of_match per match: 1

In [25]:
df[df['player_of_match'].isnull()][
    ['match_id', 'team1', 'team2', 'result']
].drop_duplicates()

        match_id                        team1                  team2   result
57068     501265             Delhi Daredevils          Pune Warriors  wickets
115599    829763  Royal Challengers Bangalore       Rajasthan Royals  wickets
121177    829813  Royal Challengers Bangalore       Delhi Daredevils  wickets
176392   1178424  Royal Challengers Bangalore       Rajasthan Royals  wickets
236750   1359519         Lucknow Super Giants    Chennai Super Kings  wickets
271126   1473481                 Punjab Kings  Kolkata Knight Riders  wickets
273705   1473492               Delhi Capitals    Sunrisers Hyderabad  wickets
274316   1473495                 Punjab Kings         Delhi Capitals  wickets

In [26]:
pom_missing_matches = df[df['player_of_match'].isnull()]['match_id'].unique()

df[df['match_id'].isin(pom_missing_matches)][
    ['match_id', 'player_of_match']
].drop_duplicates()

        match_id player_of_match
57068     501265             NaN
115599    829763             NaN
121177    829813             NaN
176392   1178424             NaN
236750   1359519             NaN
271126   1473481             NaN
273705   1473492             NaN
274316   1473495             NaN

In [27]:
print("Remaining missing values:", df['player_of_match'].isnull().sum())
print("Unique players per match:", df.groupby('match_id')['player_of_match'].nunique(dropna=True).max())

Remaining missing values: 806
Unique players per match: 1

### Player of the Match – Missing Value Treatment

The **`player_of_match`** column contained **806 missing values**. The missing values were checked at the **`match_id`** level to determine whether the player name was available in another row of the same match.

The analysis showed that these missing values belonged to matches where **`player_of_match`** was missing throughout the entire match. Therefore, the missing values could not be reliably recovered from the available dataset.

Hence, these values were **retained as `NaN`** rather than using arbitrary or assumed values.

## Result margin

In [28]:
print("Data type:", df['result_margin'].dtype)

print("\nUnique values:")
print(df['result_margin'].unique())

print("\nValue counts:")
print(df['result_margin'].value_counts(dropna=False))

print("\nStatistics:")
print(df['result_margin'].describe())

Data type: object

Unique values:
['140' '33' '9' '5' '6' '3' '66' '7' '10' '4' '13' '45' '8' '29' '18' '23'
 '41' '12' '65' '25' '1' '14' '105' '19' '75' '92' '11' '24' 'undefined'
 '27' '38' '78' '16' '53' '2' '31' '55' '98' '34' '36' '39' '17' 17 41 40
 4 5 67 24 6 23 63 8 37 2 9 14 7 13 39 57 11 35 38 22 33 21 3 16 48 29 25
 55 '26' '20' '21' '85' '32' '63' '76' '111' '82' '43' '58' '28' '74' '22'
 '42' '59' '46' '37' '47' '35' '86' '44' '48' '87' 86 130 58 15 60 65 77
 46 30 50 93 72 '15' '62' '30' '97' '138' '71' '144' '80' '51' '61' '146'
 10 20 1 19 71 64 31 102 34 '118' '40' '49' '57' '88' '60' '69' '54' 12 18
 36 75 91 52 62 54 81 '56' '112' '77' '81' 28 106 78 98 47 27 44 '50'
 '100' '83' '110']

Value counts:
result_margin
6      25255
7      21391
5      19756
8      14548
4      12945
       ...
75       211
146      211
76       204
112      189
86        17
Name: count, Length: 161, dtype: int64

Statistics:
count     278205
unique       161
top            6
freq       25255
Name: result_margin, dtype: object

In [29]:
df[df['result_margin'] == 'undefined']['result'].value_counts(dropna=False)

result
wickets    4702
Name: count, dtype: int64

In [30]:
print("Undefined values:", (df['result_margin'] == 'undefined').sum())

Undefined values: 4702

In [31]:
wicket_matches = df[df['result'] == 'wickets']

wicket_matches.groupby('match_id').agg(
    result_margin=('result_margin', 'first'),
    final_wickets_remaining=('wickets_remaining', 'last')
).head(20)

         result_margin  final_wickets_remaining
match_id
335984               9                        9
335985               5                        5
335986               5                        5
335987               6                        6
335988               9                        9
335990               3                        3
335992               7                        7
335993               9                        9
335994              10                       10
335995               4                        4
335997               7                        7
335999               7                        7
336001               8                        8
336002               5                        5
336005               8                        8
336006               6                        6
336007               7                        7
336008               7                        7
336009               4                        4
336011               8                        8

In [32]:
undefined_check = df[df['result_margin'] == 'undefined'].groupby('match_id').agg(
    result=('result', 'first'),
    final_wickets_remaining=('wickets_remaining', 'last')
)

undefined_check.head(20)

           result  final_wickets_remaining
match_id
392190    wickets                       10
419121    wickets                        9
501265    wickets                        7
598004    wickets                       10
598017    wickets                        8
729315    wickets                       10
829741    wickets                        8
829763    wickets                        3
829813    wickets                       10
1082625   wickets                       10
1175365   wickets                        9
1178424   wickets                        9
1178426   wickets                       10
1216493   wickets                       10
1216512   wickets                       10
1216517   wickets                       10
1216547   wickets                       10
1254077   wickets                       10
1359519   wickets                        3
1473469   wickets                       10

In [33]:
df.drop('result_margin', axis=1, inplace=True)

In [34]:
print('result_margin' in df.columns)

False

### Removing `result_margin`

The **`result_margin`** column was removed because it contained inconsistent data types and **4,702 `undefined` values**. The missing values could not be reliably recovered from the available records. Since this column was not essential for the planned analysis and dashboard, it was removed to maintain data quality and consistency.

## Date

In [35]:
print("Data type:", df['date'].dtype)

print("\nMissing values:", df['date'].isnull().sum())

print("\nSample values:")
print(df['date'].head(10))

print("\nUnique values:", df['date'].nunique())

Data type: object

Missing values: 0

Sample values:
0    4/18/2008
1    4/18/2008
2    4/18/2008
3    4/18/2008
4    4/18/2008
5    4/18/2008
6    4/18/2008
7    4/18/2008
8    4/18/2008
9    4/18/2008
Name: date, dtype: object

Unique values: 885

In [36]:
df.isnull().sum().sort_values(ascending=False)

fielder              268192
wicket_kind          264382
player_out           264382
required_run_rate    144302
target_score         144302
player_of_match         806
winner                  495
match_id                  0
toss_winner               0
team2                     0
toss_decision             0
season                    0
venue                     0
team1                     0
date                      0
city                      0
over                      0
bowling_team              0
batting_team              0
inning                    0
result                    0
ball                      0
bowler                    0
batter                    0
wickets_down              0
current_score             0
extras                    0
runs_scored               0
non_striker               0
current_run_rate          0
balls_remaining           0
wickets_remaining         0
dtype: int64

In [37]:
print(df[df['required_run_rate'].isnull()]['inning'].value_counts())

inning
1    144131
3        83
4        76
5         8
6         4
Name: count, dtype: int64

In [38]:
print(df[df['target_score'].isnull()]['inning'].value_counts())

inning
1    144131
3        83
4        76
5         8
6         4
Name: count, dtype: int64

In [39]:
print(
    df[df['required_run_rate'].isnull()]
    .groupby(['inning', 'result'])
    .size()
)

inning  result
1       runs       65910
        wickets    78221
3       wickets       83
4       wickets       76
5       wickets        8
6       wickets        4
dtype: int64

In [40]:
print(
    df[df['target_score'].isnull()]
    .groupby(['inning', 'result'])
    .size()
)

inning  result
1       runs       65910
        wickets    78221
3       wickets       83
4       wickets       76
5       wickets        8
6       wickets        4
dtype: int64

In [41]:
df[
    df['required_run_rate'].isnull() &
    (df['inning'] > 1)
][
    ['match_id', 'inning', 'batting_team', 'bowling_team',
     'result', 'current_score', 'target_score',
     'required_run_rate']
].drop_duplicates().head(50)

,match_id,inning,batting_team,bowling_team,result,current_score,target_score,required_run_rate
15417,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,1,NaN,NaN
15418,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,2,NaN,NaN
15419,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,3,NaN,NaN
15420,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,7,NaN,NaN
15421,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,11,NaN,NaN
15422,392190,3,Kolkata Knight Riders,Rajasthan Royals,wickets,15,NaN,NaN
15424,392190,4,Rajasthan Royals,Kolkata Knight Riders,wickets,6,NaN,NaN
15425,392190,4,Rajasthan Royals,Kolkata Knight Riders,wickets,8,NaN,NaN
15426,392190,4,Rajasthan Royals,Kolkata Knight Riders,wickets,14,NaN,NaN
15427,392190,4,Rajasthan Royals,Kolkata Knight Riders,wickets,18,NaN,NaN
30957,419121,3,Chennai Super Kings,Kings XI Punjab,wickets,1,NaN,NaN
30959,419121,3,Chennai Super Kings,Kings XI Punjab,wickets,3,NaN,NaN
30960,419121,3,Chennai Super Kings,Kings XI Punjab,wickets,9,NaN,NaN
30962,419121,4,Kings XI Punjab,Chennai Super Kings,wickets,6,NaN,NaN
30965,419121,4,Kings XI Punjab,Chennai Super Kings,wickets,10,NaN,NaN
78042,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,2,NaN,NaN
78043,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,3,NaN,NaN
78044,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,4,NaN,NaN
78045,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,10,NaN,NaN
78046,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,12,NaN,NaN
78047,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,18,NaN,NaN
78048,598004,3,Sunrisers Hyderabad,Royal Challengers Bangalore,wickets,20,NaN,NaN
78049,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,2,NaN,NaN
78050,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,3,NaN,NaN
78051,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,7,NaN,NaN
78052,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,8,NaN,NaN
78053,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,14,NaN,NaN
78054,598004,4,Royal Challengers Bangalore,Sunrisers Hyderabad,wickets,15,NaN,NaN
81211,598017,3,Royal Challengers Bangalore,Delhi Daredevils,wickets,1,NaN,NaN
81212,598017,3,Royal Challengers Bangalore,Delhi Daredevils,wickets,2,NaN,NaN
81213,598017,3,Royal Challengers Bangalore,Delhi Daredevils,wickets,3,NaN,NaN
81215,598017,3,Royal Challengers Bangalore,Delhi Daredevils,wickets,9,NaN,NaN
81216,598017,3,Royal Challengers Bangalore,Delhi Daredevils,wickets,15,NaN,NaN
81217,598017,4,Delhi Daredevils,Royal Challengers Bangalore,wickets,0,NaN,NaN
81218,598017,4,Delhi Daredevils,Royal Challengers Bangalore,wickets,4,NaN,NaN
81220,598017,4,Delhi Daredevils,Royal Challengers Bangalore,wickets,10,NaN,NaN
81221,598017,4,Delhi Daredevils,Royal Challengers Bangalore,wickets,11,NaN,NaN
99050,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,1,NaN,NaN
99051,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,2,NaN,NaN
99052,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,3,NaN,NaN
99053,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,9,NaN,NaN
99054,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,10,NaN,NaN
99055,729315,3,Kolkata Knight Riders,Rajasthan Royals,wickets,11,NaN,NaN
99056,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,1,NaN,NaN
99057,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,3,NaN,NaN
99058,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,4,NaN,NaN
99059,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,8,NaN,NaN
99060,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,9,NaN,NaN
99061,729315,4,Rajasthan Royals,Kolkata Knight Riders,wickets,11,NaN,NaN
113497,829741,3,Kings XI Punjab,Rajasthan Royals,wickets,0,NaN,NaN

### Missing Value Treatment – Target Score and Required Run Rate

The **`target_score`** and **`required_run_rate`** columns contain missing values primarily in the first innings, where these variables are not applicable because no target has been set yet.

A small number of missing values were also observed in later innings (innings 3–6), all associated with wicket-based results and special match situations. These values were retained as **NaN** because there was insufficient information to reliably derive them.

Therefore, no imputation was performed for **`target_score`** or **`required_run_rate`**.

In [42]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [43]:
## Teams name check
team_cols = [
    'team1',
    'team2',
    'toss_winner',
    'winner',
    'batting_team',
    'bowling_team'
]

for col in team_cols:
    print(f"\n{'=' * 50}")
    print(f"{col.upper()}")
    print(f"{'=' * 50}")
    print(df[col].unique())

==================================================
TEAM1
==================================================
['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']

==================================================
TEAM2
==================================================
['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru']

==================================================
TOSS_WINNER
==================================================
['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Gujarat Titans' 'Lucknow Super Giants'
 'Royal Challengers Bengaluru']

==================================================
WINNER
==================================================
['Kolkata Knight Riders' 'Chennai Super Kings' 'Delhi Daredevils'
 'Royal Challengers Bangalore' 'Rajasthan Royals' 'Kings XI Punjab'
 'Deccan Chargers' 'Mumbai Indians' 'Pune Warriors' 'Kochi Tuskers Kerala'
 nan 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']

==================================================
BATTING_TEAM
==================================================
['Kolkata Knight Riders' 'Royal Challengers Bangalore'
 'Chennai Super Kings' 'Kings XI Punjab' 'Rajasthan Royals'
 'Delhi Daredevils' 'Mumbai Indians' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Sunrisers Hyderabad'
 'Rising Pune Supergiants' 'Gujarat Lions' 'Rising Pune Supergiant'
 'Delhi Capitals' 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']

==================================================
BOWLING_TEAM
==================================================
['Royal Challengers Bangalore' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Chennai Super Kings' 'Delhi Daredevils' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']

In [44]:
print("Result values:")
print(df['result'].unique())

print("\nToss decision values:")
print(df['toss_decision'].unique())

Result values:
['runs' 'wickets']

Toss decision values:
['field' 'bat']

In [45]:
df.dtypes

match_id               int64
season                object
date                  object
city                  object
venue                 object
team1                 object
team2                 object
toss_winner           object
toss_decision         object
winner                object
result                object
player_of_match       object
inning                 int64
batting_team          object
bowling_team          object
over                   int64
ball                   int64
batter                object
bowler                object
non_striker           object
runs_scored            int64
extras                 int64
current_score          int64
wickets_down           int64
balls_remaining        int64
wickets_remaining      int64
current_run_rate     float64
required_run_rate    float64
target_score         float64
wicket_kind           object
player_out            object
fielder               object
dtype: object

In [46]:
num_cols = [
    'match_id',
    'season',
    'inning',
    'over',
    'ball',
    'runs_scored',
    'extras',
    'current_score',
    'wickets_down',
    'balls_remaining',
    'wickets_remaining',
    'current_run_rate',
    'required_run_rate',
    'target_score'
]

df[num_cols].dtypes

match_id               int64
season                object
inning                 int64
over                   int64
ball                   int64
runs_scored            int64
extras                 int64
current_score          int64
wickets_down           int64
balls_remaining        int64
wickets_remaining      int64
current_run_rate     float64
required_run_rate    float64
target_score         float64
dtype: object

In [47]:
print("Shape:", df.shape)

print("\nDuplicate rows:", df.duplicated().sum())

print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False))

Shape: (278205, 32)

Duplicate rows: 0

Missing values:
fielder              268192
wicket_kind          264382
player_out           264382
required_run_rate    144302
target_score         144302
player_of_match         806
winner                  495
match_id                  0
toss_winner               0
team2                     0
toss_decision             0
season                    0
venue                     0
team1                     0
date                      0
city                      0
over                      0
bowling_team              0
batting_team              0
inning                    0
result                    0
ball                      0
bowler                    0
batter                    0
wickets_down              0
current_score             0
extras                    0
runs_scored               0
non_striker               0
current_run_rate          0
balls_remaining           0
wickets_remaining         0
dtype: int64

In [48]:
print("VENUE LIST")
print("=" * 60)

for i, venue in enumerate(sorted(df['venue'].dropna().unique()), 1):
    print(f"{i}. {venue}")

VENUE LIST
============================================================
1. Arun Jaitley Stadium
2. Arun Jaitley Stadium, Delhi
3. Barabati Stadium
4. Barsapara Cricket Stadium, Guwahati
5. Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
6. Brabourne Stadium
7. Brabourne Stadium, Mumbai
8. Buffalo Park
9. De Beers Diamond Oval
10. Dr DY Patil Sports Academy
11. Dr DY Patil Sports Academy, Mumbai
12. Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
13. Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam
14. Dubai International Cricket Stadium
15. Eden Gardens
16. Eden Gardens, Kolkata
17. Feroz Shah Kotla
18. Green Park
19. Himachal Pradesh Cricket Association Stadium
20. Himachal Pradesh Cricket Association Stadium, Dharamsala
21. Holkar Cricket Stadium
22. JSCA International Stadium Complex
23. Kingsmead
24. M Chinnaswamy Stadium
25. M Chinnaswamy Stadium, Bengaluru
26. M.Chinnaswamy Stadium
27. MA Chidambaram Stadium
28. MA Chidambaram Stadium, Chepauk
29. MA Chidambaram Stadium, Chepauk, Chennai
30. Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur
31. Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh
32. Maharashtra Cricket Association Stadium
33. Maharashtra Cricket Association Stadium, Pune
34. Narendra Modi Stadium, Ahmedabad
35. Nehru Stadium
36. New Wanderers Stadium
37. Newlands
38. OUTsurance Oval
39. Punjab Cricket Association IS Bindra Stadium
40. Punjab Cricket Association IS Bindra Stadium, Mohali
41. Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh
42. Punjab Cricket Association Stadium, Mohali
43. Rajiv Gandhi International Stadium
44. Rajiv Gandhi International Stadium, Uppal
45. Rajiv Gandhi International Stadium, Uppal, Hyderabad
46. Sardar Patel Stadium, Motera
47. Saurashtra Cricket Association Stadium
48. Sawai Mansingh Stadium
49. Sawai Mansingh Stadium, Jaipur
50. Shaheed Veer Narayan Singh International Stadium
51. Sharjah Cricket Stadium
52. Sheikh Zayed Stadium
53. St George's Park
54. Subrata Roy Sahara Stadium
55. SuperSport Park
56. Vidarbha Cricket Association Stadium, Jamtha
57. Wankhede Stadium
58. Wankhede Stadium, Mumbai
59. Zayed Cricket Stadium, Abu Dhabi

In [49]:
venue_mapping = {

    # Delhi
    'Arun Jaitley Stadium': 'Arun Jaitley Stadium',
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    'Feroz Shah Kotla': 'Arun Jaitley Stadium',

    # Brabourne
    'Brabourne Stadium': 'Brabourne Stadium',
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',

    # DY Patil
    'Dr DY Patil Sports Academy': 'Dr DY Patil Sports Academy',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',

    # Visakhapatnam
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium':
        'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam':
        'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',

    # Eden Gardens
    'Eden Gardens': 'Eden Gardens',
    'Eden Gardens, Kolkata': 'Eden Gardens',

    # Himachal Pradesh
    'Himachal Pradesh Cricket Association Stadium':
        'Himachal Pradesh Cricket Association Stadium',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala':
        'Himachal Pradesh Cricket Association Stadium',

    # Chinnaswamy
    'M Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',

    # Chepauk
    'MA Chidambaram Stadium': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',

    # Maharaja Yadavindra Singh Stadium
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':
        'Maharaja Yadavindra Singh International Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh':
        'Maharaja Yadavindra Singh International Cricket Stadium',

    # Maharashtra Cricket Association
    'Maharashtra Cricket Association Stadium':
        'Maharashtra Cricket Association Stadium',
    'Maharashtra Cricket Association Stadium, Pune':
        'Maharashtra Cricket Association Stadium',
    'Subrata Roy Sahara Stadium':
        'Maharashtra Cricket Association Stadium',

    # Narendra Modi / Motera
    'Narendra Modi Stadium, Ahmedabad':
        'Narendra Modi Stadium',
    'Sardar Patel Stadium, Motera':
        'Narendra Modi Stadium',

    # Punjab Cricket Association
    'Punjab Cricket Association IS Bindra Stadium':
        'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali':
        'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh':
        'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association Stadium, Mohali':
        'Punjab Cricket Association IS Bindra Stadium',

    # Rajiv Gandhi
    'Rajiv Gandhi International Stadium':
        'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal':
        'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad':
        'Rajiv Gandhi International Stadium',

    # Sawai Mansingh
    'Sawai Mansingh Stadium': 'Sawai Mansingh Stadium',
    'Sawai Mansingh Stadium, Jaipur': 'Sawai Mansingh Stadium',

    # Wankhede
    'Wankhede Stadium': 'Wankhede Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',

    # Abu Dhabi
    'Sheikh Zayed Stadium': 'Zayed Cricket Stadium, Abu Dhabi',
    'Zayed Cricket Stadium, Abu Dhabi': 'Zayed Cricket Stadium, Abu Dhabi'
}

df['venue'] = df['venue'].replace(venue_mapping)

In [50]:
print("Unique venues after cleaning:", df['venue'].nunique())

for i, venue in enumerate(sorted(df['venue'].dropna().unique()), 1):
    print(f"{i}. {venue}")

Unique venues after cleaning: 36
1. Arun Jaitley Stadium
2. Barabati Stadium
3. Barsapara Cricket Stadium, Guwahati
4. Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
5. Brabourne Stadium
6. Buffalo Park
7. De Beers Diamond Oval
8. Dr DY Patil Sports Academy
9. Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
10. Dubai International Cricket Stadium
11. Eden Gardens
12. Green Park
13. Himachal Pradesh Cricket Association Stadium
14. Holkar Cricket Stadium
15. JSCA International Stadium Complex
16. Kingsmead
17. M Chinnaswamy Stadium
18. MA Chidambaram Stadium
19. Maharaja Yadavindra Singh International Cricket Stadium
20. Maharashtra Cricket Association Stadium
21. Narendra Modi Stadium
22. Nehru Stadium
23. New Wanderers Stadium
24. Newlands
25. OUTsurance Oval
26. Punjab Cricket Association IS Bindra Stadium
27. Rajiv Gandhi International Stadium
28. Saurashtra Cricket Association Stadium
29. Sawai Mansingh Stadium
30. Shaheed Veer Narayan Singh International Stadium
31. Sharjah Cricket Stadium
32. St George's Park
33. SuperSport Park
34. Vidarbha Cricket Association Stadium, Jamtha
35. Wankhede Stadium
36. Zayed Cricket Stadium, Abu Dhabi

In [ ]:
df.to_csv('ipl_cleaned_new.csv', index=False)

In [ ]:
print("Cleaned dataset saved successfully!")